app <- ShinyDriver$new("../../")
app$snapshotInit("KEGG_module_testing")

app$setInputs(loadExampleGeneDE = TRUE)
app$setInputs(loadExampleMetDE = TRUE)
app$setInputs(preprocess = "click")
app$setInputs(runAll = "click")
app$setInputs(addHighlyExpressedEdges = TRUE)
app$snapshot()
app$setInputs(metaboliteActions = "connectAtomsInsideMetabolite")
app$snapshot()
app$setInputs(metaboliteActions = "collapseAtomsIntoMetabolites")
app$snapshot()
app$setInputs(solveToOptimality = TRUE)
app$setInputs(find = "click")
app$snapshot()
