app <- ShinyDriver$new("../../")
app$snapshotInit("nodesAsMetabolites")

app$setInputs(loadExampleGeneDE = TRUE)
app$setInputs(loadExampleMetDE = TRUE)
app$setInputs(autoFindModule = FALSE)
app$setInputs(preprocess = "click")
app$setInputs(runStep1 = "click")
app$setInputs(network_type = "rhea")
app$setInputs(preprocess = "click")
app$setInputs(runStep1 = "click")
app$snapshot()
app$setInputs(network_type = "kegg")
app$setInputs(nodesAs = "metabolites")
app$setInputs(preprocess = "click")
app$setInputs(runStep1 = "click")
app$snapshot()
app$setInputs(nodesAs = "atoms")
app$setInputs(preprocess = "click")
app$setInputs(runStep1 = "click")
app$snapshot()
app$setInputs(network_type = "rhea")
app$setInputs(preprocess = "click")
app$setInputs(runStep1 = "click")
app$snapshot()
app$setInputs(nodesAs = "metabolites")
app$setInputs(preprocess = "click")
app$setInputs(runStep1 = "click")
app$snapshot()
